<div class="panel panel-default">
    <div class="panel-heading">Редактировать статью</div>
    <div class="panel-body">
        <?php
        $this->headTitle($title);
        ?>
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        <?php
        $form->setAttribute('action', $this->url('goods', array('action' => 'add')));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('name'));
        $form->get('catalog_id')->setAttributes(['class' => 'form-control']);
        echo $this->formRow($form->get('catalog_id'));
        echo $this->formRow($form->get('desc'));
        ?>
        <label>Выбрать изображение: </label>
        <span class="btn btn-primary">
            <?php echo $this->formRow($form->get('picture')); ?>
        </span>
        <?php
        echo $this->formRow($form->get('price'));
        $form->get('submitadd')->setAttribute('value', 'Добавить');
        echo $this->formSubmit($form->get('submitadd'));

        if ($this->errormessage) {
            ?>
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h3 class="panel-title">Панель сообщений</h3>
                </div>
                <div class="panel-body">
                    <?php echo "<br> $this->errormessage"; ?>
                </div>
            </div>
            <?php echo $this->form()->closeTag();
        } ?>
    </div>
</div>