<?php
$form = $this->form;
$form->setAttribute('action', $this->url('goods', array('action' => 'index')));
echo $this->form()->openTag($form);

$form->get('submitadd')->setAttributes(['class'=>'btn btn-primary']);
$form->get('submitadd')->setValue('Выбрать');
echo $this->formSubmit($form->get('submitadd'));
echo $this->form()->closeTag();
?>

<div class="panel panel-default">
    <div class="panel-heading">Список всех статей</div>
    <div class="panel-body">
        <div align="center"><a href="<?php echo $this->url('goods', array('action' => 'add')); ?>" type="button"
                               class="btn-success btn-lg">Добавить статью</a></div>
        <hr/>
        <div class="emptyCategory"></div>


        <div class="emptyCategoryEx">
            <div class="emptyCategoryInt"><?php if ($products == NULL) {
                    echo ":(";
                } ?></div>
            <br/><?php if ($products == NULL) {
                echo "Категория не содержит материалов!";
            } ?></div>

        <?php if($products) foreach ($products as $index => $product): ?>
            <div class="product-item">
                <div class="image__wrapper transparent5">
                    <img src="<?php
                    if ($product->getPicture())
                        echo $this->escapeHtml($form->getSaveToDir() . $product->getPicture());
                    else
                        echo $this->escapeHtml($form->getSaveToDir() . "noimg.png");
                    ?>" class="minimized" alt="клик для увеличения"/>
                </div>
                <div class="product-list">
                    <h4><?= $this->escapeHtml($product->getName()); ?></h4>
                    <div align="left"><?php
                        echo $this->escapeHtml(mb_substr($product->getDesc(), 0, 230) . "...");
                        ?>
                    </div>
                    <span class="price">₽ <?= $this->escapeHtml($product->getPrice()); ?></span>
                    <a href="<?php echo $this->url('goods', array('action' => 'edit', 'id' => $product->getId())); ?>"
                       class="button">Редактировать</a> | <a
                            href="<?php echo $this->url('goods', array('action' => 'delete', 'id' => $product->getId())); ?>"
                            class="button">Удалить</a>
                </div>
            </div>
        <?php endforeach; ?>

    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                            class="sr-only">Закрыть</span></button>
                <h4 class="modal-title" id="myModalLabel">Изображение</h4>
            </div>
            <div class="modal-body">
                <img class="showEx" src="" id="preview" style="width: 500px; height: 250px;">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>