<div class="panel panel-default">
    <div class="panel-heading">Удалить авто</div>
    <div class="panel-body">
        <h4>Вы уверены, что хотите удалить данный авто?</h4>
        <?php
        $this->headTitle($title);
        ?>
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        <?php
        $form->setAttribute('action', $this->url('catalogs', array('action' => 'delete', 'id' => $id)));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formSubmit($form->get('submitcatadd'));
        echo $this->form()->closeTag();

        ?>
    </div>
</div>