<!--<div class="panel panel-default">
    <div class="panel-heading">Редактировать каталог</div>
    <div class="panel-body">
        <Вопросзнакphp
/*        $form->setAttribute('action', $this->url('catalogs', array('action' => 'edit', 'id' => $id)));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('name'));
        echo $this->formRow($form->get('parent_id'));
        echo $this->formSubmit($form->get('submitcatadd'));
        echo $this->form()->closeTag();

        */?>
    </div>
</div>-->
<?php
$form = $this->form;
$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter post title here'
]);
$form->get('power')->setAttributes([
    'placeholder'=>'Type content here',
]);
$form->get('description')->setAttributes([
    'placeholder'=>'Type content here',
    'rows'=>2
]);
$form->get('submitadd')->setAttributes(['class'=>'btn btn-primary']);
$form->get('submitadd')->setValue('Сохранить');
$form->prepare();
?>

<h1>Редактирование двигателя</h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

     <div class="form-group">
            <?= $this->formLabel($form->get('power')); ?>
            <?= $this->formElement($form->get('power')); ?>
            <?= $this->formElementErrors($form->get('power')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <?= $this->formElement($form->get('submitadd')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>